env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

name: publish

on: 
  push:
    branches:
      - review-2

permissions:
  contents: read
  packages: write
  
jobs:
  build-and-publish-latest:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout the repository
          uses: actions/checkout@v4

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Log in to the Container registry
          uses: docker/login-action@v3
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        # BACKEND IMAGE
        - name: Build and push backend
          uses: docker/build-push-action@v5
          with:
            context: ./backend
            push: true
            cache-from: type=gha
            cache-to: type=gha,mode=max
            tags: |
              ${{ env.REGISTRY }}/${{ github.repository_owner }}/backend:latest
              ${{ env.REGISTRY }}/${{ github.repository_owner }}/backend:${{ github.sha }}

        # FRONTEND IMAGE
        - name: Build and push frontend
          uses: docker/build-push-action@v5
          with:
            context: ./frontend
            push: true
            cache-from: type=gha
            cache-to: type=gha,mode=max
            tags: |
              ${{ env.REGISTRY }}/${{ github.repository_owner }}/frontend:latest
              ${{ env.REGISTRY }}/${{ github.repository_owner }}/frontend:${{ github.sha }}
